spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}fc87ca51cba5a0746c84477cddde0cb90275b713959519c076eaea0834803532'

token:
  expiration_time: 864000000
  secret: user_token_default

  gateway:
    ip: 172.16.11.175
